# Generated by Django 5.0.6 on 2024-06-17 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_client_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default='profile_pics/l60Hf.png', null=True, upload_to='profile_pics/'),
        ),
    ]
