# Generated by Django 5.0.6 on 2024-06-18 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='sellers.bookcategory'),
        ),
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='books', to='sellers.bookgenre'),
        ),
        migrations.AlterField(
            model_name='bookcategory',
            name='image',
            field=models.ImageField(default='category_pics/category_default.jpg', upload_to='category_pics/'),
        ),
        migrations.AlterField(
            model_name='bookgenre',
            name='image',
            field=models.ImageField(default=' genre_pics/category_default.jpg', upload_to='genre_pics/'),
        ),
    ]
